[tool.poetry]
name = "devind_dictionaries"
version = "0.10.0"
description = "Common dictionaries for devind applications."
authors = ["Luferov Victor <lyferov@yandex.ru>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/devind-team/devind-django-dictionaries"
repository = "https://github.com/devind-team/devind-django-dictionaries"
keywords = ["django", "graphene", "dictionaries"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: Django"
]

[tool.poetry.dependencies]
python = "^3.9"
Django = ">=3.2.12,<5.0.0"
graphene-django = "^2.15.0"
requests = "^2.27.1"
beautifulsoup4 = "^4.10.0"
celery = "^5.2.5"
devind-helpers = "^0"
graphene-django-filter = "^0.6.4"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
flake8-import-order = "^0.18.1"
flake8-docstrings = "^1.6.0"
flake8-builtins = "^1.5.3"
flake8-quotes = "^3.3.1"
flake8-comprehensions = "^3.8.0"
flake8-eradicate = "^1.2.0"
flake8-simplify = "^0.19.2"
flake8-spellcheck = "^0.28.0"
pep8-naming = "^0.13.0"
flake8-use-fstring = "^1.3"
flake8-annotations = "^2.7.0"
django-seed = "^0.3.1"
coveralls = "^3.3.1"
python-dotenv = "^0.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "devind_dictionaries/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"
