[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cefeste"
version = "1.1.3"
authors = [
  { name="DAT - Mattia Centurelli", email="mcenturelli@credem.it" },
]
description = "Feature Selection and Elimination"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://dev.azure.com/credem-data/DAT/_git/ce-feste"