[tool.poetry]
name = "smartjs"
version = "0.0.8"
description = ""
authors = ["Daniel Victor <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Unidecode = "^1.3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
