[tool.poetry]
name = "cookiecutter-autodocs"
version = "1.0.0"
description = "Generate docs from your cookiecutter template"
authors = ["Andrew Herrington <andrew.the.techie@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cookiecutter_autodocs"}]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
typer = ">=0.7,<0.10"
aiofiles = "^23.1.0"
pydantic = "^1.10.7"
toml = "^0.10.2"
py-markdown-table = "^0.3.3"
rich = "^13.3.4"

[tool.poetry.scripts]
cookiecutter-autodocs = "cookiecutter_autodocs.cli:main"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.21.0"
bandit = "^1.7.5"
mypy = "^1.1.1"
pre-commit-hooks = "^4.4.0"
reorder-python-imports = "^3.9.0"
pytest-xdist = "^3.2.1"
ruff = ">=0.0.261,<0.0.266"
pre-commit = "^3.2.1"
pyupgrade = "^3.3.1"
types-aiofiles = "^23.1.0.1"
pytest-subtests = "^0.10.0"
types-toml = "^0.10.8.6"
pyflakes = "^3.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.bandit]
exclude_dirs = ["tests", "noxfile.py", ".github/scripts"]


[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
target-version = "py38"

[tool.mypy]
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[tool.pytest.ini_options]
addopts = "-n 4  --cov=cookiecutter_autodocs --cov-report xml:.coverage.xml --cov-report=term-missing"
