[tool.poetry]
name = "smartjs"
version = "0.1.0"
description = "Project for creation of javascript, html and style elements for use in web pages."
authors = ["Daniel Victor <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Unidecode = "^1.3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
