[tool.poetry]
name = "attribtool"
version = "1.0.0"
description = "Base classes for restricting the dynamic creation of attributes in inheriting classess."
authors = ["Jacek Kotlarski <szumak@virthost.pl>"]
maintainers = ["Jacek Kotlarski <szumak@virthost.pl>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Szumak75/AttribTool"
classifiers = [
	"Programming Language :: Python :: 3",
	"Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = "^3.7"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.4"
autopep8 = "^2.0.2"
flake8 = "^6.0.0"
pyflakes = "^3.0.1"
pycodestyle = "^2.10.0"
pydocstyle = "^6.3.0"
yapf = "^0.33.0"
typing-extensions = "^4.5.0"
nose = "^1.3.7"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
