[tool.poetry]
name = "amdgpu-stats"
version = "0.1.16"
description = "A module/TUI for AMD GPU statistics"
authors = ["Josh Lay <pypi@jlay.io>"]
repository = "https://github.com/joshlay/amdgpu_stats"
license = "MIT"
readme = "README.md"
documentation = "https://amdgpu-stats.readthedocs.io/en/latest/"

[tool.poetry.dependencies]
python = "^3.9"
textual = ">=0.18.0"
humanfriendly = ">=10.0"

[tool.poetry.scripts]
amdgpu-stats = "amdgpu_stats:textual_run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
