[build-system]
requires = ["setuptools>=67.0"]
build-backend = "setuptools.build_meta"
[project]
name = "rapidocr_openvinogpu"
version = "0.0.8"
description="RapidOCR OpenVINO GPU version (GPU version only)"
requires-python = ">=3.7"
dependencies = [
    "pyclipper>=1.2.1", "openvino>=2022.2.0",
    "opencv_python>=4.5.1.48", "numpy>=1.19.3",
    "six>=1.15.0", "Shapely>=1.7.1", 'PyYAML', 'Pillow'
]
keywords=[
    'ocr,text_detection,text_recognition,db,onnxruntime,paddleocr,openvino,rapidocr'
]
classifiers=[
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
authors = [
  {name = "Jagadish", email = "jagadishkmahendran@gmail.com"},
]
license = {file = "LICENSE.txt"}
[project.urls]
repository = "https://github.com/jaggiK/rapidocr_openvinogpu"
issues = "https://github.com/jaggiK/rapidocr_openvinogpu/issues"