[project]
name = "threadsafe_shell"
version = "1.3.0"
authors = [
  { name="Calico Kalamari", email="kalamariking@proton.me" },
]
description = "A pure-python, thread-safe, queue-based logging and user input module"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/KalamariKing/threadsafe-shell"
"Bug Tracker" = "https://github.com/KalamariKing/threadsafe-shell/issues"