[tool.poetry]
name = "simon-trans-database-models"
version = "0.2.0"
description = ""
authors = ["Pintér Tamás <tamas.pinter@pannonszoftver.hu>"]

[tool.poetry.dependencies]
python = "^3.8"
sqlalchemy = "1.3.18"
marshmallow = "3.14.1"

[tool.poetry.dev-dependencies]
pre-commit = "^3.3.1"
poetry = "^1.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
