[tool.poetry]
name = "firepup650"
version = "1.0.9"
description = "Replit source"
authors = ["Firepup650"]

[tool.poetry.dependencies]
python = "^3.8"
fkeycapture = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"