[tool.poetry]
name = "plutous"
version = "0.0.2"
description = "Plutous Library"
packages = [{include = "plutous"}]
authors = ["Cheun Hong <cheunhong@plutous.io>"]
readme = "README.md"
license="MIT"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.10"
SQLAlchemy = ">=2.0.12"
typer = ">=0.9.0"
alembic = ">=1.10.4"
pydantic = ">=1.10.7"

[tool.poetry.group.dev.dependencies]
black = ">=23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"